path:
  RAW_DATA_PATH: "./data/raw/"
  PROCESSED_DATA_PATH: "./data/processed/"
  FILES_PATH: "./artifacts/files/"

dataloader:
  image_path: "./data/raw/dataset.zip"
  channels: 3
  image_size: 224
  batch_size: 4
  split_size: 0.30

VAE:
  in_channels: 3
  out_channels: 128 # It should be like 128, 256, 512