path:
  RAW_DATA_PATH: "./data/raw/"
  PROCESSED_DATA_PATH: "./data/processed/"
  FILES_PATH: "./artifacts/files/"

dataloader:
  image_path: "./data/raw/dataset.zip"
  channels: 3
  image_size: 256
  batch_size: 4
  split_size: 0.30

VAE:
  channels: 3
  image_size: 256

trainer:
  epochs: 100
  lr: 0.001
  weight_decay: 0.0001
  beta1: 0.5
  beta2: 0.999
  momentum: 0.95
  step_size: 10
  gamma: 0.85
  adam: True
  SGD: False
  device: "cuda"
  verbose: True
  lr_scheduler: False
  weight_init: False
  l1_regularization: False
  l2_regularization: False
  MLFlow: True