path:
  RAW_DATA_PATH: "./data/raw/"
  PROCESSED_DATA_PATH: "./data/processed/"
  FILES_PATH: "./artifacts/files/"
  TRAIN_MODELS: "./artifacts/checkpoints/train_models/"
  TEST_MODELS: "./artifacts/checkpoints/best_model/"
  TRAIN_IMAGES_PATH: "./artifacts/outputs/train_images/"
  VALID_IMAGES_PATH: "./artifacts/outputs/test_image/"
  TRAIN_HISTORY_PATH: "./artifacts/metrics/"

dataloader:
  image_path: "./data/raw/dataset.zip"
  channels: 3
  image_size: 256
  batch_size: 4
  split_size: 0.30

VAE:
  channels: 3
  image_size: 256

trainer:
  epochs: 2000      
  lr: 0.002
  weight_decay: 0.0001
  beta1: 0.5
  beta2: 0.999
  momentum: 0.95
  step_size: 10
  gamma: 0.85
  adam: True
  SGD: False
  device: "mps"
  verbose: True
  lr_scheduler: False
  weight_init: False
  l1_regularization: False
  l2_regularization: False
  MLFlow: True

tester:
  model: "best" 
  device: "mps"